package ru.ibs.api;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.Test;
import ru.ibs.basetest.QualitSandboxBaseTest;
import ru.ibs.utils.Utils;

public class RunTest {
    Logger LOG = LogManager.getLogger("");

    @Test
    public void test() {
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        LOG.info("в начале теста");
        try {
            Thread.sleep(5000);
//            Utils.getQSPid();
//            Thread.sleep(10000);
            LOG.info("В теле теста, после слипа");
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        LOG.info("Тест завершен");
    }
}
